"""add publisher tables

Revision ID: c250c3b52322
Revises: e22206edcc83
Create Date: 2023-07-28 07:01:10.584398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c250c3b52322'
down_revision = 'e22206edcc83'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publishers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cutoff', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discord_guild_credentials',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('publisher_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discord_guild_credentials')
    op.drop_table('publishers')
    # ### end Alembic commands ###
