from rules.contrib.models import RulesModel
from django.db import models

from .utils import create_pk_field
from cafe.libs.gen_id import IDType

from cafe.models import User, Club

from django.core.serializers.json import DjangoJSONEncoder

from django.utils.timezone import now

class RDLevelPrefillResult(RulesModel):
    """
    A prefill result stores the initial analysis of an rdzip file.
    """
    id = create_pk_field(IDType.PREFILL)
    # url of the level that's being prefilled
    url = models.TextField(default="")
    # datetime that the prefill was initiated. this is used to cleanup old prefill results.
    created_at = models.DateTimeField(blank=False, default=now)
    # version of the prefill task that ran.
    version = models.IntegerField()
    # task will set to True when the task is complete.
    ready = models.BooleanField(default=False)
    # generated by the prefill task.
    data = models.JSONField(default=dict, encoder=DjangoJSONEncoder)
    # the user that initiated the prefill.
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # the club that the prefill is allowed to be used for.
    club = models.ForeignKey(Club, on_delete=models.CASCADE)
    # errors that occurred during the prefill.
    errors = models.TextField(default="")
