# Generated by Django 5.0.7 on 2024-11-06 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClubRDLevel',
        ),
    ]
