# Generated by Django 5.0.7 on 2024-11-06 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_delete_clubrdlevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdlevelprefillresult',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.club'),
        ),
        migrations.AlterField(
            model_name='rdlevelprefillresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
