# Generated by Django 5.0.6 on 2024-05-29 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0006_alter_user_options_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('theme_pref', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], max_length=100)),
            ],
        ),
    ]
