# Generated by Django 5.0.6 on 2024-06-01 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0007_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
