# Generated by Django 5.0.6 on 2024-06-02 04:11

import cafe.libs.gen_id
import django.db.models.deletion
import functools
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0008_delete_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.CharField(default=functools.partial(cafe.libs.gen_id.gen_id, *(cafe.libs.gen_id.IDType['CLUB'],), **{}), max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClubMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], max_length=10)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(through='cafe.ClubMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClubRDLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.club')),
                ('rdlevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.rdlevel')),
            ],
        ),
        migrations.AddConstraint(
            model_name='clubmembership',
            constraint=models.UniqueConstraint(fields=('user', 'club'), name='unique_user_and_club'),
        ),
        migrations.AddConstraint(
            model_name='clubrdlevel',
            constraint=models.UniqueConstraint(fields=('rdlevel', 'club'), name='unique_rdlevel_and_club'),
        ),
    ]
