# Generated by Django 5.0.7 on 2024-07-22 23:49

import cafe.libs.gen_id
import functools
import rules.contrib.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0012_discordguild'),
    ]

    operations = [
        migrations.CreateModel(
            name='RDLevelPrefillResult',
            fields=[
                ('id', models.CharField(default=functools.partial(cafe.libs.gen_id.gen_id, *(cafe.libs.gen_id.IDType['PREFILL'],), **{}), max_length=24, primary_key=True, serialize=False)),
                ('ready', models.BooleanField(default=False)),
                ('data', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
