# Generated by Django 5.0.7 on 2024-08-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0015_rdlevelprefillresult_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdlevelprefillresult',
            name='version',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rdlevelprefillresult',
            name='data',
            field=models.BinaryField(default=b''),
        ),
    ]
