# Generated by Django 5.0.7 on 2024-08-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0016_rdlevelprefillresult_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdlevelprefillresult',
            name='url',
            field=models.TextField(default=''),
        ),
    ]
