# Generated by Django 5.0.7 on 2024-10-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0019_rdlevel_rdzip_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdlevelprefillresult',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
