# Generated by Django 5.0.7 on 2024-10-09 00:54

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0020_alter_rdlevelprefillresult_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdlevelprefillresult',
            name='data',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
