# Generated by Django 5.0.7 on 2024-10-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0021_alter_rdlevelprefillresult_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdlevel',
            name='icon_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
