# Generated by Django 5.0.7 on 2024-10-09 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0022_alter_rdlevel_icon_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdlevel',
            name='submitter',
            field=models.ForeignKey(default='u_admin', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
