# Generated by Django 5.0.7 on 2024-10-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0023_rdlevel_submitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdlevel',
            name='sha1',
            field=models.TextField(unique=True),
        ),
    ]
