# Generated by Django 5.0.7 on 2024-10-09 14:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0025_rdlevelprefillresult_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdlevelprefillresult',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
