# Generated by Django 5.0.7 on 2024-11-05 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0026_alter_rdlevelprefillresult_created_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='cafe__user__username_startswith_u_',
        ),
    ]
