# Generated by Django 5.0.7 on 2024-11-05 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cafe', '0027_remove_user_cafe__user__username_startswith_u_'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('username__startswith', 'u-')), name='cafe__user__username_startswith_u_'),
        ),
    ]
