# Generated by Django 5.1.4 on 2025-01-19 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0010_clubmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(through='cafe.ClubMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
