# Generated by Django 5.1.4 on 2025-01-28 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0012_clubinvite'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordGuild',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discord_guilds', to='cafe.club')),
            ],
        ),
    ]
