# Generated by Django 5.1.4 on 2025-01-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0013_discordguild'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordguild',
            name='name',
            field=models.TextField(blank=True),
        ),
    ]
