# Generated by Django 5.1.4 on 2025-02-02 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0014_discordguild_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discordguild',
            name='name',
        ),
    ]
