# Generated by Django 5.1.4 on 2025-02-22 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0017_rdlevelprefillresult_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdlevelprefillresult',
            name='task_id',
        ),
    ]
