# Generated by Django 5.2 on 2025-04-25 11:51

import cafe.models.id_utils
import django.db.models.deletion
import rules.contrib.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0018_remove_rdlevelprefillresult_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RDLevel',
            fields=[
                ('id', models.CharField(default=cafe.models.id_utils.generate_rdlevel_id, max_length=7, primary_key=True, serialize=False)),
                ('artist', models.TextField()),
                ('artist_tokens', models.JSONField()),
                ('song', models.TextField()),
                ('song_alt', models.TextField(blank=True)),
                ('seizure_warning', models.BooleanField()),
                ('description', models.TextField(blank=True)),
                ('hue', models.FloatField()),
                ('authors', models.JSONField()),
                ('authors_raw', models.TextField()),
                ('max_bpm', models.IntegerField()),
                ('min_bpm', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('single_player', models.BooleanField()),
                ('two_player', models.BooleanField()),
                ('last_updated', models.DateTimeField()),
                ('tags', models.JSONField()),
                ('has_classics', models.BooleanField()),
                ('has_oneshots', models.BooleanField()),
                ('has_squareshots', models.BooleanField()),
                ('has_freezeshots', models.BooleanField()),
                ('has_freetimes', models.BooleanField()),
                ('has_holds', models.BooleanField()),
                ('has_skipshots', models.BooleanField()),
                ('has_window_dance', models.BooleanField()),
                ('sha1', models.TextField(unique=True)),
                ('rdlevel_sha1', models.TextField()),
                ('is_animated', models.BooleanField()),
                ('rdzip_url', models.TextField()),
                ('image_url', models.TextField()),
                ('thumb_url', models.TextField()),
                ('icon_url', models.TextField(blank=True, default='')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.club')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
