# Generated by Django 5.2 on 2025-05-10 13:15

import cafe.models.id_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0020_rdlevel_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='id',
            field=models.CharField(default=cafe.models.id_utils.generate_club_id, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rdlevel',
            name='id',
            field=models.CharField(default=cafe.models.id_utils.generate_rdlevel_id, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rdlevelprefillresult',
            name='id',
            field=models.CharField(default=cafe.models.id_utils.generate_rdlevel_prefill_id, max_length=8, primary_key=True, serialize=False),
        ),
    ]
