# Generated by Django 5.2 on 2025-07-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0023_historicalclub_historicalrdlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrdlevel',
            name='artist_raw',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historicalrdlevel',
            name='authors_raw',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historicalrdlevel',
            name='rd_md5',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historicalrdlevel',
            name='song_raw',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='rdlevel',
            name='artist_raw',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='rdlevel',
            name='authors_raw',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='rdlevel',
            name='rd_md5',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='rdlevel',
            name='song_raw',
            field=models.TextField(default=''),
        ),
    ]
