# Generated by Django 5.2 on 2025-12-03 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0029_replace_api_key_with_iter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrdlevel',
            name='has_classics',
        ),
        migrations.RemoveField(
            model_name='historicalrdlevel',
            name='has_freetimes',
        ),
        migrations.RemoveField(
            model_name='historicalrdlevel',
            name='has_freezeshots',
        ),
        migrations.RemoveField(
            model_name='historicalrdlevel',
            name='has_holds',
        ),
        migrations.RemoveField(
            model_name='historicalrdlevel',
            name='has_oneshots',
        ),
        migrations.RemoveField(
            model_name='historicalrdlevel',
            name='has_skipshots',
        ),
        migrations.RemoveField(
            model_name='historicalrdlevel',
            name='has_squareshots',
        ),
        migrations.RemoveField(
            model_name='historicalrdlevel',
            name='has_window_dance',
        ),
        migrations.RemoveField(
            model_name='rdlevel',
            name='has_classics',
        ),
        migrations.RemoveField(
            model_name='rdlevel',
            name='has_freetimes',
        ),
        migrations.RemoveField(
            model_name='rdlevel',
            name='has_freezeshots',
        ),
        migrations.RemoveField(
            model_name='rdlevel',
            name='has_holds',
        ),
        migrations.RemoveField(
            model_name='rdlevel',
            name='has_oneshots',
        ),
        migrations.RemoveField(
            model_name='rdlevel',
            name='has_skipshots',
        ),
        migrations.RemoveField(
            model_name='rdlevel',
            name='has_squareshots',
        ),
        migrations.RemoveField(
            model_name='rdlevel',
            name='has_window_dance',
        ),
    ]
