# Generated by Django 5.2 on 2025-12-17 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0031_historicalrdlevel_approval_notes_private_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBlend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_date', models.DateField(db_index=True, unique=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.rdlevel')),
            ],
            options={
                'verbose_name': 'Daily Blend',
                'verbose_name_plural': 'Daily Blends',
                'ordering': ['-featured_date'],
            },
        ),
    ]
