# Generated by Django 5.2 on 2025-12-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0033_add_is_private_to_rdlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrdlevel',
            name='prefill_version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rdlevel',
            name='prefill_version',
            field=models.IntegerField(default=0),
        ),
    ]
