# Generated by Django 5.2 on 2025-12-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0034_historicalrdlevel_prefill_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrdlevel',
            name='prefill_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='rdlevel',
            name='prefill_version',
            field=models.IntegerField(default=1),
        ),
    ]
