# Generated by Django 5.2 on 2026-01-05 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0038_rdlevelprefillresult_go_to_prepost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdlevelprefillresult',
            name='level',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe.rdlevel'),
        ),
    ]
