# Generated by Django 5.2 on 2026-04-02 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0042_dailyblendrandompool'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyblendconfiguration',
            name='paused',
            field=models.BooleanField(default=False),
        ),
    ]
