# Generated by Django 5.2 on 2026-04-08 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0043_dailyblendconfiguration_paused'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddSession',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('interaction_token', models.TextField()),
                ('phase', models.IntegerField(default=1)),
                ('data', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
