# Generated by Django 5.2 on 2026-04-08 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0044_addsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addsession',
            name='data',
        ),
        migrations.RemoveField(
            model_name='addsession',
            name='user',
        ),
    ]
