# Generated by Django 5.2.13 on 2026-05-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0053_drop_discordaddlevelsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdlevelprefillresult',
            name='overwrite_metadata',
            field=models.BooleanField(default=False),
        ),
    ]
