# Generated by Django 5.2.14 on 2026-05-25 03:56

from django.db import migrations

def forwards_func(apps, schema_editor):
    BlendPool = apps.get_model("cafe", "BlendPool")
    db_alias = schema_editor.connection.alias
    BlendPool.objects.using(db_alias).create(
        id="bdefault",
        name="Default Pool"
    )

def reverse_func(apps, schema_editor):
    BlendPool = apps.get_model("cafe", "BlendPool")
    db_alias = schema_editor.connection.alias
    BlendPool.objects.using(db_alias).filter(id="bdefault").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0057_blendpool'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
