# Generated by Django 5.2.14 on 2026-05-25 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0058_default_blendpool'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyblendrandompool',
            name='pool',
            field=models.ForeignKey(default='bdefault', on_delete=django.db.models.deletion.CASCADE, to='cafe.blendpool'),
            preserve_default=False,
        ),
    ]
