# Generated by Django 5.2.14 on 2026-05-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0060_dailyblend_pool_alter_dailyblend_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blendpool',
            name='weighting_system',
            field=models.CharField(choices=[('flat', 'Flat'), ('aging', 'Aging')], default='flat', max_length=100),
        ),
    ]
