# Generated by Django 5.2.14 on 2026-05-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0062_dailyblendrandompool_tickets'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dailyblendrandompool',
            constraint=models.CheckConstraint(condition=models.Q(('tickets__gt', 0)), name='tickets_greater_than_zero'),
        ),
    ]
