# Generated by Django 6.0.6 on 2026-08-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0064_dailyblendconfiguration_reporting_webhook_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_rddirect',
            field=models.BooleanField(default=False),
        ),
    ]
