# Generated by Django 5.0.6 on 2024-05-22 07:12

import cafe.models.user
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', cafe.models.user.CafeUserManager()),
            ],
        ),
    ]
