# Generated by Django 5.0.6 on 2024-06-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0009_club_clubmembership_club_members_clubrdlevel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin')], max_length=10),
        ),
    ]
