# Generated by Django 5.1.4 on 2025-01-26 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0011_club_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField(choices=[('owner', 'Owner'), ('admin', 'Admin')])),
                ('expiry', models.DateTimeField()),
                ('code', models.CharField(max_length=100)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.club')),
            ],
        ),
    ]
