# Generated by Django 5.1.4 on 2025-02-08 10:31

import cafe.models.id_utils
import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
import rules.contrib.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0015_remove_discordguild_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RDLevelPrefillResult',
            fields=[
                ('id', models.CharField(default=cafe.models.id_utils.generate_rdlevel_prefill_id, max_length=7, primary_key=True, serialize=False)),
                ('url', models.TextField(default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.IntegerField()),
                ('prefill_type', models.CharField(max_length=100)),
                ('ready', models.BooleanField(default=False)),
                ('data', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('errors', models.TextField(default='')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
