# Generated by Django 5.1.4 on 2025-02-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0016_rdlevelprefillresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdlevelprefillresult',
            name='task_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
