# Generated by Django 5.2 on 2025-05-14 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0021_alter_club_id_alter_rdlevel_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdlevel',
            name='authors_raw',
        ),
    ]
