# Generated by Django 5.2 on 2025-05-15 12:32

import cafe.models.id_utils
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0022_remove_rdlevel_authors_raw'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalClub',
            fields=[
                ('id', models.CharField(db_index=True, default=cafe.models.id_utils.generate_club_id, max_length=8)),
                ('name', models.CharField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical club',
                'verbose_name_plural': 'historical clubs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRDLevel',
            fields=[
                ('id', models.CharField(db_index=True, default=cafe.models.id_utils.generate_rdlevel_id, max_length=8)),
                ('artist', models.TextField()),
                ('artist_tokens', models.JSONField()),
                ('song', models.TextField()),
                ('song_alt', models.TextField(blank=True)),
                ('seizure_warning', models.BooleanField()),
                ('description', models.TextField(blank=True)),
                ('hue', models.FloatField()),
                ('authors', models.JSONField()),
                ('max_bpm', models.IntegerField()),
                ('min_bpm', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('single_player', models.BooleanField()),
                ('two_player', models.BooleanField()),
                ('last_updated', models.DateTimeField()),
                ('tags', models.JSONField()),
                ('has_classics', models.BooleanField()),
                ('has_oneshots', models.BooleanField()),
                ('has_squareshots', models.BooleanField()),
                ('has_freezeshots', models.BooleanField()),
                ('has_freetimes', models.BooleanField()),
                ('has_holds', models.BooleanField()),
                ('has_skipshots', models.BooleanField()),
                ('has_window_dance', models.BooleanField()),
                ('sha1', models.TextField(db_index=True)),
                ('rdlevel_sha1', models.TextField()),
                ('is_animated', models.BooleanField()),
                ('rdzip_url', models.TextField()),
                ('image_url', models.TextField()),
                ('thumb_url', models.TextField()),
                ('icon_url', models.TextField(blank=True, default='')),
                ('approval', models.IntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('club', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cafe.club')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submitter', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical rd level',
                'verbose_name_plural': 'historical rd levels',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
