# Generated by Django 5.2 on 2025-10-28 07:57

import cafe.models.id_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0025_alter_user_theme_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='id',
            field=models.CharField(default=cafe.models.id_utils.generate_club_id, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicalclub',
            name='id',
            field=models.CharField(db_index=True, default=cafe.models.id_utils.generate_club_id, max_length=20),
        ),
    ]
