# Generated by Django 5.2 on 2025-10-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0026_alter_club_id_alter_historicalclub_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_key',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, unique=True),
        ),
    ]
