# Generated by Django 5.2 on 2025-10-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0028_alter_user_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='api_key',
        ),
        migrations.AddField(
            model_name='user',
            name='api_key_iter',
            field=models.IntegerField(default=0),
        ),
    ]
