# Generated by Django 5.2 on 2025-12-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0030_remove_historicalrdlevel_has_classics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrdlevel',
            name='approval_notes_private',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='historicalrdlevel',
            name='approval_notes_public',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='rdlevel',
            name='approval_notes_private',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='rdlevel',
            name='approval_notes_public',
            field=models.TextField(blank=True, default=''),
        ),
    ]
