# Generated by Django 5.2 on 2025-12-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0032_dailyblend'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyblend',
            options={'ordering': ['-featured_date']},
        ),
        migrations.AddField(
            model_name='historicalrdlevel',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rdlevel',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
