# Generated by Django 5.2 on 2025-12-26 12:07

from django.db import migrations


def bump_prefill_version(apps, schema_editor):
    RDLevel = apps.get_model('cafe', 'RDLevel')
    RDLevel.objects.filter(prefill_version=0).update(prefill_version=1)


def reverse_bump_prefill_version(apps, schema_editor):
    # Reverse migration - set back to 0
    RDLevel = apps.get_model('cafe', 'RDLevel')
    RDLevel.objects.filter(prefill_version=1).update(prefill_version=0)


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0035_alter_historicalrdlevel_prefill_version_and_more'),
    ]

    operations = [
        migrations.RunPython(bump_prefill_version, reverse_bump_prefill_version),
    ]
