# Generated by Django 5.2 on 2026-01-05 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0037_historicalrdlevel_has_burnshots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdlevelprefillresult',
            name='go_to_prepost',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rdlevelprefillresult',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe.rdlevel'),
        ),
    ]
