# Generated by Django 5.2 on 2026-01-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0039_alter_rdlevelprefillresult_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyblend',
            name='blended',
            field=models.BooleanField(default=False),
        ),
    ]
