# Generated by Django 5.2 on 2026-01-07 11:29

import rules.contrib.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0040_dailyblend_blended'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBlendConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_urls', models.TextField(blank=True, default='')),
                ('jsonata_script', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
