# Generated by Django 5.2 on 2026-04-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0045_remove_addsession_data_remove_addsession_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='addsession',
            name='selected_attachment_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
