# Generated by Django 5.2 on 2026-04-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0046_addsession_selected_attachment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='addsession',
            name='attachments',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
