# Generated by Django 5.2 on 2026-04-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0047_addsession_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='addsession',
            name='add_type',
            field=models.CharField(default='new', max_length=10),
        ),
    ]
