# Generated by Django 5.2 on 2026-04-09 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0048_addsession_add_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='addsession',
            name='prefill',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe.rdlevelprefillresult'),
        ),
    ]
