# Generated by Django 5.2 on 2026-04-13 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0050_remove_discord_interaction_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='addsession',
            name='user',
            field=models.ForeignKey(default='usteward', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
