# Generated by Django 5.2 on 2026-04-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0051_addsession_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addsession',
            name='phase',
            field=models.IntegerField(choices=[(1, 'Selecting Attachment'), (2, 'Selecting Type'), (3, 'Uploading'), (4, 'Complete'), (5, 'Error Level Not Found'), (6, 'Error No Permission'), (7, 'Error Duplicate')], default=1),
        ),
    ]
