# Generated by Django 5.2.14 on 2026-05-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0054_rdlevelprefillresult_overwrite_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_pr_preference',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('all', 'All')], default='approved', max_length=100),
        ),
    ]
