# Generated by Django 5.2.14 on 2026-05-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0055_user_default_pr_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedGuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_id', models.TextField(unique=True)),
                ('reason', models.TextField(blank=True)),
                ('banned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
