# Generated by Django 5.2.14 on 2026-05-25 03:55

import cafe.models.id_utils
import rules.contrib.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0056_banned_guild'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlendPool',
            fields=[
                ('id', models.CharField(default=cafe.models.id_utils.generate_blend_pool_id, max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField()),
            ],
            options={
                'abstract': False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
