# Generated by Django 5.2.14 on 2026-05-25 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0059_dailyblendrandompool_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyblend',
            name='pool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe.blendpool'),
        ),
        migrations.AlterField(
            model_name='dailyblend',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe.rdlevel'),
        ),
        migrations.AddConstraint(
            model_name='dailyblend',
            constraint=models.CheckConstraint(condition=models.Q(('level__is_null', False), ('pool__is_null', False), _connector='OR'), name='at_least_one_of_level_or_pool_is_not_null'),
        ),
    ]
