# Generated by Django 5.2.14 on 2026-05-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0061_blendpool_weighting_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyblendrandompool',
            name='tickets',
            field=models.IntegerField(default=1),
        ),
    ]
