# Generated by Django 6.0.5 on 2026-06-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0063_dailyblendrandompool_tickets_greater_than_zero'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyblendconfiguration',
            name='reporting_webhook_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
